# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "smartdict"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sergey Potapov"]
  s.date = "2012-06-10"
  s.description = "Simple dictinionary written in Ruby"
  s.email = "blake131313@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "GPL-LICENSE.txt",
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "smartdict.gemspec"
  ]
  s.homepage = "http://github.com/greyblake/smartdict"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple dictinionary written in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<smartdict-core>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<smartdict-gtk>, ["~> 0.1.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<smartdict-core>, ["~> 0.1.0"])
      s.add_dependency(%q<smartdict-gtk>, ["~> 0.1.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<smartdict-core>, ["~> 0.1.0"])
    s.add_dependency(%q<smartdict-gtk>, ["~> 0.1.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

